{% set version = "0.1.10" %}

package:
  name: cmake-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cmake-language-server/cmake_language_server-{{ version }}.tar.gz
  sha256: dbc627dc1e549fc7414f459bdb340812acd84a0c8727b92e73c4bd348e6311bf

build:
  entry_points:
    - cmake-language-server = cmake_language_server.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - pygls

test:
  imports:
    - cmake_language_server
  commands:
    - pip check
    - cmake-language-server --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/regen100/cmake-language-server
  summary: CMake LSP Implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
